version: '3.1'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '9001:8025'

    redis:
        image: 'redis:alpine'

    postgres:
        image: 'postgres:15-alpine'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - POSTGRES_USER=vacancy
            - POSTGRES_PASSWORD=P@ssword
            - POSTGRES_DB=laravel_db
        ports:
            - '9004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '9000:80'

    php-fpm:
        build: deploy/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './deploy/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
